### ISSUE TITLE
Display problem with zoom keys

### ISSUE THREAD

**Issue by 4812162024283240** [mentat-is/gulpui-web#39]
I am using two monitors with the following resolutions:

- 1920 x 1080
- 2560 x 1600
On both, I encounter the following display and functionality issues:

1- The "Zoom fit" button displays the full range of available logs, but the older logs get hidden behind the left section where the uploaded file names are listed. It is impossible to select those events unless the view is adjusted.
2 - I have uploaded around 30 different log files, and the zoom buttons in the bottom-left section cover the names of some logs, preventing me from reading their names and interacting with them.

**Comment by Mireg-V** [comment]
@4812162024283240 
Could you provide more details about how you expect the correct logic to function? It would also help if you could share a video or some screenshots of the issue to better understand the problem. This way, I can suggest a more tailored solution.

**Comment by 4812162024283240** [comment]
When I click on "Zoom Fit," the view adjusts to fit my monitor, but some of the logs (the older ones) get hidden behind the file names, making them unclickable. Below is an image of the issue:

![image](https://github.com/user-attachments/assets/6dd15aa5-e2bf-4d8c-9ad6-3c629bd2f1b9)

When I upload a large list of files, some of them end up behind the zoom buttons, and I can no longer read the file names or interact with the logs beneath them. Below is another image of the issue:

![image](https://github.com/user-attachments/assets/d00c34b7-6440-4024-91ea-b8153c1016ff)

Let me know if this is clearer now or if you need any additional information.
I think leaving a small space dedicated to the zoom buttons, preventing them from overlapping with the uploaded log files, could be helpful.

**Comment by Mireg-V** [comment]
Thanks. Will fix 🫡
